"use client";
import {useEffect,useState} from 'react';
import {Activity,ArrowUpRight,Bot,ChevronDown,Radio,Wallet,Zap} from 'lucide-react';
import type {AgentConsoleData} from '@/lib/agent-console-types';
import {AGENT_MODELS} from '@/lib/agent-models';
import {money} from '@/lib/types';

function ago(at:number|null,now:number){if(!at)return 'Not recorded';const seconds=Math.max(0,Math.floor((now-at)/1000));return seconds<10?'Just now':seconds<60?`${seconds}s ago`:seconds<3600?`${Math.floor(seconds/60)}m ago`:`${Math.floor(seconds/3600)}h ago`;}
export default function AgentConsole({mint}:{mint:string}){
 const [data,setData]=useState<AgentConsoleData|null>(null),[error,setError]=useState(''),[now,setNow]=useState(Date.now()),[tab,setTab]=useState<'all'|'decisions'|'transactions'>('all');
 useEffect(()=>{const controller=new AbortController();let loading=false;
  async function load(){if(loading||document.hidden)return;loading=true;try{const r=await fetch(`/api/token/${encodeURIComponent(mint)}/agent-console`,{cache:'no-store',signal:controller.signal}),body=await r.json() as AgentConsoleData&{error?:string};if(!r.ok)throw new Error(body.error||'Agent updates unavailable.');setData(body);setError('');setNow(Date.now());}catch(e){if(!controller.signal.aborted)setError((e as Error).message);}finally{loading=false;}}
  setData(null);load();const timer=setInterval(load,2000);document.addEventListener('visibilitychange',load);return()=>{controller.abort();clearInterval(timer);document.removeEventListener('visibilitychange',load);};
 },[mint]);
 const workerFresh=!!data?.lastWorkerAt&&now-data.lastWorkerAt<120000,stale=!!data&&(!workerFresh||now-data.observedAt>15000);
 const status=!data?'Connecting':data.paused?'Paused':!data.activated?'Awaiting activation':stale?'Updates delayed':data.running?'Analyzing':data.jobs.length?'Processing':data.budget.mode==='paused'?'Awaiting AI budget':data.budget.mode==='economy'?'Economy mode':'Monitoring';
 const events=data?.events.filter(e=>tab==='all'||(tab==='transactions'?e.kind.startsWith('transaction'):['model_requested','proposal','decision','blocked','observing','error'].includes(e.kind)))||[];
 const lastDecision=data?.events.find(e=>['decision','blocked','error','observing','awaiting_funding','worker_waiting'].includes(e.kind));
 return <section className="agent-console" id="agent-console" aria-label="Live agent console">
  <header className="console-heading"><div><span className="eyebrow"><Radio size={13}/> ON THE JOB</span><h2>Inside the agent.</h2><p>Real checks. Model decisions. On-chain receipts.</p></div><span className={`console-status ${stale||error?'is-delayed':''}`}><i/>{error?'Connection interrupted':status}</span></header>
  <div className="console-current"><Bot size={22}/><div><strong>{AGENT_MODELS.find(m=>m.id===data?.model)?.name||'Liquidity agent'}</strong><p>{!data?(error?'Agent activity is temporarily unavailable. Retrying the connection…':'Connecting to the agent’s activity feed…'):data.paused?'Execution is paused. Existing receipts remain visible.':!data.activated?'Watching fees accumulate toward the $20 activation threshold.':!workerFresh?'The worker has not reported recently. This page cannot confirm current execution.':data.running?'A decision cycle is in progress. Its result will appear below.':data.jobs[0]?.message|| (data.jobs.length?'Processing earned-fee operations. Follow the transaction receipts below.':lastDecision?.message)||'Watching verified market data and available earned-fee budget.'}</p></div></div>
  <div className="console-metrics"><div><span>Worker check-in</span><strong>{ago(data?.lastWorkerAt??null,now)}</strong></div><div><span>Market observation</span><strong>{ago(data?.market.lastObservedAt??null,now)}</strong></div><div><span>Paid model calls</span><strong>{data?.budget.callCount??'—'}</strong></div><div><span>AI budget left</span><strong>{data?money(data.budget.remainingUsd,false):'—'}</strong></div></div>
  <div className="console-notes"><Activity size={14}/><p>{!data?'Verified market checks, funding and decisions appear here once the agent connects.':data.phase==='bonding'?'During bonding, native Meteora controls the liquidity curve. The agent watches the market and manages earned fees; range changes begin after graduation.':'The agent manages additional DLMM liquidity from earned fees. The original graduated position remains locked.'} {data?.budget.mode==='economy'?'Paid decisions slow down to preserve available AI runway. Market monitoring continues.':''}</p></div>
  <div className="console-tabs" role="tablist" aria-label="Agent activity filters">{(['all','decisions','transactions'] as const).map(t=><button role="tab" aria-selected={tab===t} key={t} onClick={()=>setTab(t)}>{t==='all'?'All activity':t==='decisions'?'AI decisions':'Transactions'}</button>)}<span>Latest first · live updates</span></div>
  {error&&<p className="console-error" role="status">{error} {data?'Showing the last received records.':'No activity records received yet.'}</p>}
  <div className="console-feed" role="log" aria-live="off" tabIndex={0} aria-label="Recorded agent activity">{events.length?events.map(e=><article className={`console-event ${['blocked','error','worker_waiting','execution_waiting'].includes(e.kind)?'is-warning':''}`} key={e.id}><span className="console-event-icon">{e.kind.startsWith('transaction')?<Wallet size={14}/>:e.kind==='proposal'||e.kind==='model_requested'?<Bot size={14}/>:<Activity size={14}/>}</span><div><div className="console-event-meta"><span>{e.kind.replaceAll('_',' ')}</span><time dateTime={new Date(e.at).toISOString()} title={new Date(e.at).toLocaleString()}>{new Date(e.at).toLocaleTimeString()}</time></div><p>{e.message}</p>{e.signature&&<a href={`https://solscan.io/tx/${e.signature}`} target="_blank" rel="noreferrer">View transaction <ArrowUpRight size={12}/></a>}</div></article>):<div className="console-empty"><Radio size={22}/><strong>{data?'No recorded activity in this view yet.':error?'Activity connection unavailable.':'Loading recorded activity…'}</strong><p>New checks, decisions and transactions will appear here as they happen.</p></div>}</div>
  <details className="console-funding" open><summary><span><Zap size={16}/> AI funding</span><ChevronDown size={15}/></summary><div className="console-funding-body"><div className="console-funding-stats"><div><span>Earned AI allocation</span><strong>{data?money(data.budget.earnedUsd,false):'—'}</strong></div><div><span>Verified model spend</span><strong>{data?money(data.budget.spentUsd,false):'—'}</strong></div><div><span>SolCard deposits</span><strong>{data?.funding.deposits??'—'} <small>{data?.funding.pendingDeposits?`${data.funding.pendingDeposits} pending`:''}</small></strong></div></div><p>{data?.funding.message||'Waiting for the funding monitor.'}</p><small>Funding check: {ago(data?.funding.checkedAt??null,now)}{data?.funding.checkedAt&&now-data.funding.checkedAt>120000?' · status may be stale':''}</small>{data&&data.budget.committedUsd>data.budget.spentUsd+.000001&&<p>Some model costs are reserved while OpenRouter confirms usage.</p>}<p className="console-funding-explainer">AI starts with a 50% earned-fee allocation. Its share adapts to measured usage and treasury size, with 10% buyback and 20% reserves protected. Deposits fund SolCard; OpenRouter auto-recharge adds credits. Each coin has its own spending budget within the shared OpenRouter account.</p>{data?.funding.signature&&<a href={`https://solscan.io/tx/${data.funding.signature}`} target="_blank" rel="noreferrer">Latest confirmed funding transfer <ArrowUpRight size={13}/></a>}</div></details>
 </section>;
}
