"use client";
import {useEffect,useState} from 'react';
import {Check,Coins,ExternalLink} from 'lucide-react';
import type {AgentFees,FeeAmount} from '@/lib/fee-types';
import {money} from '@/lib/types';
export default function AgentFeePanel({mint}:{mint:string}){
 const [fees,setFees]=useState<AgentFees|null>(null),[error,setError]=useState(''),[now,setNow]=useState(Date.now());
 useEffect(()=>{const controller=new AbortController();let running=false;async function load(){if(running||document.hidden)return;running=true;try{const r=await fetch(`/api/token/${encodeURIComponent(mint)}/fees`,{cache:'no-store',signal:controller.signal}),d=await r.json() as AgentFees & {error?:string};if(!r.ok)throw new Error(d.error||'Fee data is temporarily unavailable.');setFees(d);setError('');}catch(e){if(!controller.signal.aborted)setError((e as Error).message);}finally{running=false;}}load();const timer=setInterval(load,2000),clock=setInterval(()=>setNow(Date.now()),1000);document.addEventListener('visibilitychange',load);window.addEventListener('thicc:trade',load);return()=>{controller.abort();clearInterval(timer);clearInterval(clock);document.removeEventListener('visibilitychange',load);window.removeEventListener('thicc:trade',load);};},[mint]);
 const activation=fees?.activation,seconds=fees?.collection.nextCheckAt?Math.max(0,Math.ceil((fees.collection.nextCheckAt-now)/1000)):null;
 const value=(amount:FeeAmount|undefined)=>amount?money(amount.usd,false):'—';
 return <div className="agent-fee-panel"><div className={`activation-progress ${activation?.active?'is-active':''}`}><div><strong>{activation?.active?<><Check size={14}/> Agent activated</>:'Agent activation'}</strong><span>{activation?`${Math.min(100,activation.percent).toFixed(1)}%`:'—'}</span></div><div className="activation-track" role="progressbar" aria-label="Verified fees toward agent activation" aria-valuemin={0} aria-valuemax={20} aria-valuenow={Math.min(20,activation?.claimedUsd||0)}><span style={{width:`${activation?.percent||0}%`}}/></div><p>{activation?`${money(activation.claimedUsd,false)} / $20.00`:'Loading verified fees…'}<small>{activation?.active?'Activation threshold reached':'Finalized, priced claims unlock the agent'}</small></p></div><div className="fee-metrics" aria-live="polite">{[{label:'Fees held by agent',value:fees?.held,note:'Earned fees still allocated in its wallet'},{label:'Pending collection',value:fees?.pending,note:'Unclaimed fees in Meteora positions'},{label:'Total fees earned',value:fees?.total,note:'Lifetime collected + currently unclaimed'}].map(row=><div key={row.label}><span>{row.label}<small>{row.note}</small></span><strong>{value(row.value)}</strong>{!!row.value?.tokens.length&&<small className="fee-token-amounts">{row.value.tokens.map(t=>`${t.amount} ${t.symbol}`).join(' · ')}</small>}</div>)}</div><div className="collection-status"><Coins size={14}/><span>{fees?.collection.status==='paused'?'Collection paused':fees?.collection.status==='confirming'?'Collection transaction settling':seconds===null?'Automatic collection · every 30s':seconds>0?`Next collection check in ${seconds}s`:'Collection check due'}<small>{fees?.collection.lastCheckedAt?`Last checked ${new Date(fees.collection.lastCheckedAt).toLocaleTimeString()}`:'Waiting for the collector'}</small></span>{fees?.collection.signature&&<a href={`https://solscan.io/tx/${fees.collection.signature}`} target="_blank" rel="noreferrer" aria-label="View latest fee collection transaction"><ExternalLink size={14}/></a>}</div><p className="helper">USD estimates use current prices. Creator gas and LP principal are excluded. Claims wait for wallet availability and transaction confirmation.</p>{(error||fees?.collection.message)&&<p className="helper negative" role="status">{error?`Updates delayed: ${error}`:fees?.collection.message}</p>}</div>;
}
