import {ArrowUpRight,Bot,ImagePlus} from "lucide-react";
import type {CoinDetail} from "@/lib/coin-types";
import {AGENT_MODELS} from "@/lib/agent-models";
import {money} from "@/lib/types";
import BondingProgress from "./bonding-progress";
export default function CoinDirectory({coins,grid}:{coins:CoinDetail[];grid:boolean}){
 if(!grid)return <div className="table-wrap"><table><thead><tr><th>Coin</th><th>Market cap</th><th>Volume 24h</th><th>Liquidity</th><th>Bonding</th><th/></tr></thead><tbody>{coins.map(c=><tr key={c.mint}><td><a className="token-cell" href={`/token/${c.mint}`}><span className="directory-icon">{c.imageUrl?<img src={c.imageUrl} alt=""/>:<ImagePlus size={17}/>}</span><span><strong>{c.name}</strong><small>${c.symbol} · {c.quoteSymbol} pair</small></span></a></td><td>{money(c.marketCapUsd)}</td><td>{money(c.volume24hUsd)}</td><td>{money(c.liquidityUsd)}</td><td><BondingProgress status={c.status} percent={c.bondingPct}/></td><td><a href={`/token/${c.mint}`} aria-label={`Open ${c.symbol}`}><ArrowUpRight size={14}/></a></td></tr>)}</tbody></table></div>;
 return <div className="coin-directory">{coins.map(c=><a className="directory-card" href={`/token/${c.mint}`} key={c.mint}><div className="directory-card-head"><span className="directory-icon">{c.imageUrl?<img src={c.imageUrl} alt=""/>:<ImagePlus size={23}/>}</span><div><strong>{c.name}</strong><small>${c.symbol} · {c.quoteSymbol}</small></div><ArrowUpRight size={15}/></div><p>{c.description||"A THICC coin with a dedicated liquidity agent."}</p><div className="directory-cap"><span>Market cap</span><strong>{money(c.marketCapUsd)}</strong><small>Graduation {money(c.graduationUsd)}</small></div><div className="directory-metrics"><div><span>24h volume</span><strong>{money(c.volume24hUsd)}</strong></div><div><span>Liquidity</span><strong>{money(c.liquidityUsd)}</strong></div></div><div className="directory-agent"><Bot size={13}/>{AGENT_MODELS.find(m=>m.id===c.model)?.name||"Agent pending"}</div><BondingProgress status={c.status} percent={c.bondingPct}/></a>)}</div>;
}
