"use client";
import {useEffect,useRef,useState} from "react";
import {Check,LoaderCircle,Search,ShieldCheck} from "lucide-react";
export const SOL_MINT="So11111111111111111111111111111111111111112";
export type QuoteToken={mint:string;symbol:string;name:string;category:string;categoryLabel:string;decimals:number;launchable:boolean;logoUrl:string|null;symbolAmbiguous?:boolean};
const categories=[{key:"solana",label:"Solana"},{key:"xstock",label:"xStocks"},{key:"prestock",label:"PreStocks"},{key:"backpack",label:"Sunrise"}];
function QuoteLogo({token}:{token:QuoteToken}){const [failed,setFailed]=useState(false);return <span className={`quote-icon ${token.category}`}>{token.logoUrl&&!failed?<img src={token.logoUrl} alt="" loading="lazy" referrerPolicy="no-referrer" onError={()=>setFailed(true)}/>:token.symbol.slice(0,2)}</span>;}
export default function QuoteSelector({value,onChange}:{value:string;onChange:(token:QuoteToken)=>void}){
 const [quotes,setQuotes]=useState<QuoteToken[]>([]),[category,setCategory]=useState("solana"),[search,setSearch]=useState(""),[error,setError]=useState("");
 const selection=useRef({value,onChange});selection.current={value,onChange};
 useEffect(()=>{const controller=new AbortController();fetch("/api/quotes",{signal:controller.signal}).then(async r=>{const d=await r.json() as {quotes:QuoteToken[];error:string};if(!r.ok)throw new Error(d.error);setQuotes(d.quotes);const sol=d.quotes.find(q=>q.mint===SOL_MINT&&q.launchable);if(!selection.current.value&&sol)selection.current.onChange(sol);}).catch(e=>{if(!controller.signal.aborted)setError(e.message);});return()=>controller.abort();},[]);
 const filtered=quotes.filter(q=>q.category===category&&`${q.symbol} ${q.name} ${q.mint}`.toLowerCase().includes(search.toLowerCase()));
 const selected=quotes.find(q=>q.mint===value);
 return <div className="quote-selector"><div className="quote-label">Pair your token with<span>{selected?`${selected.symbol} selected`:"SOL is the default"}</span></div><div className="quote-tabs">{categories.map(c=><button type="button" key={c.key} className={category===c.key?"selected":""} aria-pressed={category===c.key} onClick={()=>{setCategory(c.key);setSearch("");}}>{c.label}<small>{quotes.filter(q=>q.category===c.key).length||"…"}</small></button>)}</div><div className="search"><Search size={14}/><input aria-label="Search quote tokens" placeholder="Search name, symbol, or mint address" value={search} onChange={e=>setSearch(e.target.value)}/></div>{error?<p className="negative" role="alert">{error}</p>:!quotes.length?<div className="quote-loading"><LoaderCircle size={18} className="spin"/> Loading supported quotes…</div>:<div className="quote-grid">{filtered.map(q=><button type="button" className={value===q.mint?"selected":""} aria-pressed={value===q.mint} disabled={!q.launchable} title={q.mint} onClick={()=>onChange(q)} key={q.mint}><QuoteLogo token={q}/><span><strong>{q.symbol}{q.mint===SOL_MINT&&<em className="default-quote">Default</em>}</strong><small>{q.name}</small>{q.symbolAmbiguous&&<small className="mint-hint">{q.mint.slice(0,5)}…{q.mint.slice(-4)}</small>}</span>{value===q.mint&&<Check size={13}/>}</button>)}{!filtered.length&&<p className="helper">No quote tokens match this search.</p>}</div>}<p className="helper"><ShieldCheck size={12}/> Exact mint addresses from the live registry. Launch compatibility is verified separately.</p></div>;
}
