"use client";
import {useEffect,useRef,useState} from "react";
import {CandlestickChart,Maximize2,RefreshCw} from "lucide-react";
import {createChart,CandlestickSeries,HistogramSeries,ColorType,CrosshairMode,type IChartApi,type ISeriesApi,type UTCTimestamp} from "lightweight-charts";
import {CHART_INTERVALS,type Candle,type ChartInterval} from "@/lib/candles";
export default function TokenChart({mint,symbol,enabled}:{mint:string;symbol:string;enabled:boolean}){
 const container=useRef<HTMLDivElement>(null),chart=useRef<IChartApi|null>(null),candles=useRef<ISeriesApi<"Candlestick">|null>(null),volume=useRef<ISeriesApi<"Histogram">|null>(null),fitted=useRef(false);
 const [interval,setIntervalValue]=useState<ChartInterval>("1m"),[count,setCount]=useState(0),[error,setError]=useState(""),[loading,setLoading]=useState(false),[last,setLast]=useState<Candle|null>(null),[updated,setUpdated]=useState<number|null>(null),[refresh,setRefresh]=useState(0);
 useEffect(()=>{if(!container.current)return;const c=createChart(container.current,{autoSize:true,height:420,layout:{background:{type:ColorType.Solid,color:"#ffffff"},textColor:"#8c977f",fontSize:10,fontFamily:"DM Sans, sans-serif",attributionLogo:true},grid:{vertLines:{color:"#f0f2eb"},horzLines:{color:"#f0f2eb"}},rightPriceScale:{borderColor:"#e6eadf",scaleMargins:{top:.12,bottom:.23}},timeScale:{borderColor:"#e6eadf",timeVisible:true,secondsVisible:true,rightOffset:5},crosshair:{mode:CrosshairMode.Normal,vertLine:{color:"#bdc6b1",labelBackgroundColor:"#667757"},horzLine:{color:"#bdc6b1",labelBackgroundColor:"#667757"}},localization:{priceFormatter:(p:number)=>p===0?"$0":`$${p.toLocaleString("en-US",{maximumSignificantDigits:6})}`}});
  const series=c.addSeries(CandlestickSeries,{upColor:"#69a477",downColor:"#f1855a",wickUpColor:"#69a477",wickDownColor:"#f1855a",borderVisible:false,priceFormat:{type:"price",precision:10,minMove:0.0000000001}});
  const bars=c.addSeries(HistogramSeries,{priceFormat:{type:"volume"},priceScaleId:"volume",lastValueVisible:false,priceLineVisible:false});c.priceScale("volume").applyOptions({scaleMargins:{top:.82,bottom:0},visible:false});
  c.subscribeCrosshairMove(p=>{const point=p.seriesData.get(series);if(point&&"open" in point)setLast({...point,time:Number(point.time),volume:0});});
  chart.current=c;candles.current=series;volume.current=bars;return()=>{c.remove();chart.current=null;candles.current=null;volume.current=null;};
 },[]);
 useEffect(()=>{const controller=new AbortController();let active=true,running=false;setCount(0);setLast(null);setError("");setUpdated(null);fitted.current=false;candles.current?.setData([]);volume.current?.setData([]);chart.current?.applyOptions({timeScale:{secondsVisible:interval==="1s"}});
  async function load(){if(!enabled||running)return;running=true;setLoading(true);try{const r=await fetch(`/api/token/${encodeURIComponent(mint)}/candles?interval=${interval}`,{signal:controller.signal,cache:"no-store"});const data=await r.json() as {candles:Candle[];error?:string;lastTradeAt:number|null};if(!r.ok)throw new Error(data.error||"Chart data unavailable.");if(!active)return;candles.current?.setData(data.candles.map(c=>({...c,time:c.time as UTCTimestamp})));volume.current?.setData(data.candles.map(c=>({time:c.time as UTCTimestamp,value:c.volume,color:c.close>=c.open?"#a1c8a980":"#f3b99a80"})));setCount(data.candles.length);setLast(data.candles.at(-1)||null);setUpdated(data.lastTradeAt);setError("");if(data.candles.length&&!fitted.current){chart.current?.timeScale().fitContent();fitted.current=true;}}catch(e){if(active&&!controller.signal.aborted)setError((e as Error).message);}finally{running=false;if(active)setLoading(false);}}
  load();const timer=setInterval(load,interval==="1s"?1000:5000);return()=>{active=false;controller.abort();clearInterval(timer);};
 },[mint,enabled,interval,refresh]);
 const price=(p:number)=>`$${p.toLocaleString("en-US",{maximumSignificantDigits:5})}`;
 return <section className="token-chart-panel"><div className="token-chart-heading"><span><CandlestickChart size={17}/><strong>{symbol} / USD</strong><small>Candles</small></span><div>{(Object.keys(CHART_INTERVALS) as ChartInterval[]).map(value=><button key={value} className={interval===value?"selected":""} aria-pressed={interval===value} onClick={()=>setIntervalValue(value)}>{value}</button>)}<button aria-label="Refresh chart" onClick={()=>setRefresh(n=>n+1)}><RefreshCw size={13} className={loading?"spin":""}/></button><button aria-label="Fit chart to data" onClick={()=>chart.current?.timeScale().fitContent()}><Maximize2 size={13}/></button></div></div><div className="chart-ohlc">{last?<>{[{label:"O",value:last.open},{label:"H",value:last.high},{label:"L",value:last.low},{label:"C",value:last.close}].map(x=><span key={x.label}>{x.label} <strong>{price(x.value)}</strong></span>)}</> : <span>OHLC and volume from recorded swaps</span>}</div><div className="token-chart-container"><div ref={container} className="token-chart-canvas"/>{!count&&<div className="token-chart-empty"><CandlestickChart size={28}/><strong>{loading?"Loading market history…":error?"Chart data unavailable":"Waiting for recorded trades"}</strong><p>{error||(!enabled?"A verified token launch is required before market data can appear.":`No verified trades have been indexed in this ${interval} chart window.`)}</p></div>}</div><div className="chart-source"><span>{updated?`Last trade ${new Date(updated).toLocaleTimeString()}`:"No indexed trade history"} · {interval} candles</span><a href="https://www.tradingview.com/" target="_blank" rel="noreferrer">Charts by TradingView</a></div></section>;
}
