"use client";
import {useEffect,useState} from "react";
import {ArrowUpRight,LoaderCircle} from "lucide-react";
import {signWalletTransaction} from "@/lib/wallet-transactions";
export default function TradePanel({mint,symbol,quoteSymbol}:{mint:string;symbol:string;quoteSymbol:string}){
 const [side,setSide]=useState<"buy"|"sell">("buy"),[amount,setAmount]=useState(""),[wallet,setWallet]=useState(""),[busy,setBusy]=useState(false),[error,setError]=useState(""),[signature,setSignature]=useState(""),[status,setStatus]=useState("");
 useEffect(()=>{fetch("/api/account").then(async r=>{if(r.ok){const d=await r.json() as {wallet?:string};setWallet(d.wallet||"");}}).catch(()=>{});},[]);
 async function trade(){setBusy(true);setError("");setSignature("");try{const account=await fetch("/api/account"),identity=await account.json() as {wallet?:string};if(!account.ok||!identity.wallet)throw new Error("Connect your wallet using the navbar first.");setWallet(identity.wallet);
  const response=await fetch("/api/trade/prepare",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({mint,side,amount,slippageBps:50})}),prepared=await response.json() as {error?:string;operationId:string;transaction:string};if(!response.ok)throw new Error(prepared.error);setStatus("Approve the trade in your wallet.");
  const transaction=await signWalletTransaction(prepared.transaction,identity.wallet),sent=await fetch("/api/trade/submit",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({operationId:prepared.operationId,transaction})}),result=await sent.json() as {error?:string;signature:string;status:string};if(!sent.ok)throw new Error(result.error);setSignature(result.signature);setStatus("Submitted · waiting for confirmation.");
  for(let i=0;i<90;i++){await new Promise(resolve=>setTimeout(resolve,2000));const r=await fetch("/api/tx/status",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({signature:result.signature})}),d=await r.json() as {status?:{err:unknown;confirmationStatus:string}};if(d.status?.err)throw new Error("Trade failed on-chain. Your swap was not executed.");if(d.status?.confirmationStatus==="finalized"){setStatus("Trade finalized. Chart data updates after indexing.");setAmount("");window.dispatchEvent(new Event("thicc:trade"));return;}}
  setStatus("Confirmation is taking longer than usual. Check the transaction link before retrying.");
 }catch(e){setError((e as Error).message);setStatus("");}finally{setBusy(false);}}
 return <section className="panel trade-panel"><div className="trade-tabs">{(["buy","sell"] as const).map(s=><button key={s} className={side===s?"selected":""} type="button" disabled={busy} onClick={()=>setSide(s)}>{s==="buy"?"Buy":"Sell"} {symbol}</button>)}</div><label className="field">Amount · {side==="buy"?quoteSymbol:symbol}<input inputMode="decimal" placeholder="0.00" value={amount} disabled={busy} onChange={e=>setAmount(e.target.value)}/></label><p className="helper">Maximum slippage 0.5% · your wallet approves each trade.</p><button className="primary full" disabled={busy||!/^\d+(\.\d+)?$/.test(amount)||Number(amount)<=0} onClick={trade}>{busy?<LoaderCircle size={15} className="spin"/>:null}{busy?"Processing…":`${side==="buy"?"Buy":"Sell"} ${symbol}`}</button>{status&&<p className="helper" role="status">{status}</p>}{error&&<p className="negative" role="alert">{error}</p>}{signature&&<a className="rail-link" href={`https://solscan.io/tx/${signature}`} target="_blank" rel="noreferrer">View transaction <ArrowUpRight size={14}/></a>}</section>;
}
