import {nativeAgentState} from "./native-agent";

import {database,event,HttpError,poolData} from "./server";
import {askModel,getCredits} from "./openrouter";
import {validateProposal,validatePolicy,type Policy,type Market} from "./engine";
export type AgentRow={id:string;owner:string;pool_address:string;pool_name:string;wallet:string;position_address:string;model:string;policy:string;status:string;last_run:number|null};
export async function runAgent(row:AgentRow){const now=Date.now();const lease=await database().prepare("UPDATE agents SET lease_until=? WHERE id=? AND status='active' AND lease_until<? AND (last_run IS NULL OR last_run<?)").bind(now+90000,row.id,now,now-300000).run();if(!lease.meta.changes)throw new HttpError(409,"Agent is paused, already running, or waiting for its five-minute cooldown.");try{const policy=JSON.parse(row.policy) as Policy;if(validatePolicy(policy).length)throw new HttpError(400,"Agent risk policy is invalid.");const vault=await nativeAgentState(row.id,row.pool_address,row.position_address);if(!vault.active||vault.claimedUsdMicros<20_000_000n){await event(row.owner,row.id,"awaiting_fees",`Agent activates automatically at $20 in verified claimed fees. Current total: $${(Number(vault.claimedUsdMicros)/1e6).toFixed(2)}.`);return {status:"awaiting_fees"};}if(vault.poolKind!=="dlmm"){await event(row.owner,row.id,"observing","Agent fee rights verified. Waiting for the DBC market adapter before liquidity decisions.");return {status:"observing"};}const credits=await getCredits();if(credits.remaining<=0)throw new HttpError(402,"OpenRouter credits are exhausted.");const pool=await poolData(row.pool_address);const history=await database().prepare("SELECT price,created_at FROM snapshots WHERE agent_id=? AND created_at>? ORDER BY created_at DESC LIMIT 12").bind(row.id,now-3600000).all<{price:number;created_at:number}>();const prices=history.results.map(p=>p.price);const previous=prices[0];const change=previous?(pool.current_price/previous-1)*100:0;const returns=prices.slice(0,-1).map((p,i)=>(p/prices[i+1]-1)*100);const volatility=returns.length?Math.sqrt(returns.reduce((sum,n)=>sum+n*n,0)/returns.length):0;await database().prepare("INSERT INTO snapshots(id,agent_id,price,created_at) VALUES(?,?,?,?)").bind(crypto.randomUUID(),row.id,pool.current_price,Date.now()).run();
 // A freshly fetched indexer response is not proof of a fresh on-chain observation.
 // Until enough on-chain observations exist, only hold recommendations may pass.
 const market:Market={price:pool.current_price,volatility,buyShare:50,depthUsd:pool.tvl,ageSeconds:Math.ceil((Date.now()-now)/1000),priceMovePct:change};
 if(prices.length<3){await event(row.owner,row.id,"observing",`Collecting market observations (${prices.length+1}/4). No liquidity action taken.`);return {status:"observing"};}
 const proposal=await askModel(row.model,market,policy);const errors=validateProposal(proposal,market,policy,600);
 if(proposal.action!=="hold")errors.push("Execution awaits fresh on-chain flow, reserve balances, and a constrained signer.");
 await event(row.owner,row.id,errors.length?"blocked":"decision",errors.length?errors.join(" "):proposal.reason,{proposal,market});return {proposal,errors};
 }catch(error){await event(row.owner,row.id,"error",error instanceof HttpError?error.message:"Agent cycle failed. No transaction was sent.");throw error;}finally{await database().prepare("UPDATE agents SET last_run=?,lease_until=0 WHERE id=?").bind(Date.now(),row.id).run();}}
