export type DocSection={title:string;paragraphs:string[];items?:string[]};
export type DocPage={slug:string;title:string;summary:string;sections:DocSection[]};
export const DOCS:DocPage[]=[
 {slug:"overview",title:"Liquidity that keeps working.",summary:"THICC is building a launchpad where each coin has a dedicated AI liquidity manager. The objective is useful market depth, measurable execution, and fee-funded operations.",sections:[
  {title:"What THICC is",paragraphs:["A token launch creates a market. It does not automatically create a good market. Liquidity can be too thin, placed far from the trading price, or left unchanged while the market moves. THICC brings token launches, liquidity monitoring, and agent decisions into one system.","Each coin selects one of four agent models: Fable, Astra, Opus 5.5, or GPT Sol 6.1. These product choices map to verified OpenRouter model IDs pinned in code. A missing or unavailable model is not silently replaced."]},
  {title:"The lifecycle",paragraphs:["Creators provide their coin identity and select a quote token and agent. The platform defines the economics. After launch, the agent builds a verified record of earned fees and begins reasoning when that total reaches $20."],items:["Launch: fixed supply, native Meteora curve, dedicated agent fee recipient.","Observe: gather pool state, depth, flow, volatility, fees, and operating balances.","Decide: propose a liquidity action with its reasoning and expected costs.","Validate: enforce deterministic limits and verify transaction effects.","Measure: publish observed activity and compare it with an explicitly estimated unmanaged baseline."]},
  {title:"What is available today",paragraphs:["THICC creates a native Meteora bonding curve, stores coin metadata, assigns fee rights to a dedicated agent wallet, and supports wallet-approved trades. The background worker indexes finalized swaps, claims fees, and executes earned-fee workflows.","Deployments need working RPC, pricing, inference, and custody configuration. A submitted transaction is not reported as completed until its finalized receipt is available. External-service outages can pause individual actions. A form preview is not a launched token."]},
  {title:"What success means",paragraphs:["The goal is more usable liquidity around the active trading price, less avoidable slippage, disciplined capital allocation, and transparent operating costs. Success must be demonstrated with measured results. Higher fees or more rebalances alone do not prove that an agent helped holders or traders."]}
 ]},
 {slug:"liquidity",title:"Why liquidity gets thin.",summary:"THICC aims to reduce avoidable liquidity gaps. It cannot guarantee deep liquidity, eliminate volatility, or create capital that does not exist.",sections:[
  {title:"Depth matters more than a headline number",paragraphs:["Total value locked is the value of assets in a pool. It does not tell you how much is available near the current price. A concentrated position can contain considerable capital while contributing little to a trade taking place outside its active range.","Traders experience this as price impact, slippage, or poor execution. A small purchase can move the price sharply when there is little sell-side inventory close to the market. A large displayed TVL does not remove that problem."]},
  {title:"What an agent can improve",paragraphs:["A liquidity manager can inspect where capital sits and propose moving part of it toward the range where trading is happening. In a quieter market, a narrower range can increase capital efficiency. In a volatile market, a wider range can reduce the frequency with which a position becomes inactive.","THICC allocates earned fees to reinvest a fixed portion of earned fees and retain a reserve for later changes. Compounding adds real earned assets; it is not an artificial increase in reported TVL. Keeping a reserve can help the agent react without relocating its entire position."],items:["Reposition liquidity when the active price moves away from its range.","Preserve reserves for volatility and operational needs.","Evaluate the expected benefit against swap costs, gas, and model costs.","Hold when available observations cannot justify an action."]},
  {title:"Trade-offs the agent must consider",paragraphs:["Tighter ranges usually provide more depth per unit of capital while the price stays inside them. They can also leave the position out of range sooner and create more frequent rebalancing needs. Wider ranges trade some capital efficiency for broader coverage.","Increasing a trading fee can raise revenue per unit of volume while also discouraging trades. Rebalancing can realize losses, pay spreads, or expose transactions to adverse execution. The best decision can be to do nothing."]},
  {title:"Why liquidity problems cannot be eliminated",paragraphs:["An agent cannot guarantee buyers, sell inventory it does not hold, prevent all abrupt price changes, or make illiquid quote assets liquid. It cannot remove impermanent loss, token restrictions, exchange outages, or the possibility that liquidity providers withdraw.","THICC should be assessed as a system for managing available liquidity under constraints. It is not a price floor, an insurance product, a guaranteed return, or a promise that a coin can always be sold at a particular price."]}
 ]},
 {slug:"launches",title:"From an idea to a market.",summary:"A simple creator flow backed by fixed platform economics, exact quote-token addresses, and native Meteora launch infrastructure.",sections:[
  {title:"What the creator enters",paragraphs:["Provide a coin name, ticker, image, description, and optional website, X, and Telegram links. Select the AI agent and the quote token. SOL is selected by default. The launch page includes an identity preview card.","Supply, starting trading fee, curve parameters, fee ownership, and gas policy are not creator-editable inputs. The server rejects requests that attempt to override economic settings."]},
  {title:"Fixed launch settings",paragraphs:["Every launch is designed around a fixed one-billion-token supply with nine decimals, a 2% initial trading fee for new launches, and a graduation target equivalent to a 250 SOL market cap. USD is the primary display unit; SOL appears as the denomination behind that target.","Market cap is token price multiplied by the relevant token supply. A 250 SOL market-cap target is not a requirement that the creator deposit 250 SOL, nor does it mean the curve must collect exactly 250 SOL. Curve configuration determines the corresponding reserve threshold."]},
  {title:"Quote tokens and conversion",paragraphs:["The registry includes Solana assets, xStocks, PreStocks, and Sunrise tokens. Selection is by exact mint address, not just ticker, because different assets can share a symbol. Logos come from the live registry.","A registry entry does not by itself prove that a token is compatible with a particular pool. Token programs, decimals, badges, transfer restrictions, and pool support must be checked before a transaction can be prepared. SOL/USD is fetched live; stale or malformed data is rejected. Non-SOL launches additionally require a fresh verified quote-token price.","Quote amounts must be fixed when the launch is configured. A later exchange-rate change must not silently rewrite an already deployed curve. A live USD equivalent is a display conversion, not an additional migration trigger."]},
  {title:"Bonding progress",paragraphs:["Homepage coin cards show progress from actual curve quote reserves relative to the configured migration threshold. Progress is capped at 100%. Reaching the threshold can mean ready to graduate; the card says Bonded only after the chain reports migration.","Meteora's current native DBC graduation path leads to DAMM v2. DLMM uses a different liquidity model and needs a separate integration if capital is subsequently managed there. THICC must not describe a DAMM pool as a DLMM pool."]},
  {title:"Fee rights and initial gas",paragraphs:["The no-custom-program design assigns native Meteora partner fee rights to a dedicated agent wallet and sets the coin creator's fee allocation to zero. The launch wallet initially provides 0.02 SOL for agent gas, in addition to transaction fees and required account rent.","Assignment must be verified from finalized on-chain configuration before a coin is listed as a THICC launch. A submitted signature or an unsigned transaction is not enough."]}
 ]},
 {slug:"agents",title:"Observe. Reason. Validate. Act.",summary:"The language model proposes a strategy. The execution layer decides whether that proposal is permitted and sufficiently supported by evidence.",sections:[
  {title:"Activation at $20",paragraphs:["Agent activation depends on at least $20 in verified claimed trading fees. Wallet deposits, creator gas funding, token-price appreciation, and unclaimed fee estimates do not count toward that threshold.","Every fee receipt needs a finalized transaction, the correct pool and recipient, and a valid valuation. This separates economic activity from someone simply transferring funds to the agent wallet."]},
  {title:"What the agent watches",paragraphs:["The intended observation set includes price, trading volume, realized volatility, buy/sell flow, liquidity depth near the active price, current position ranges, earned fees, available reserves, and gas balance.","Unknown values must remain unknown. A model should not receive invented flow measurements or treat the time an indexer responded as proof that the underlying market observation is fresh. Missing evidence can require the system to hold."]},
  {title:"The decision loop",paragraphs:["An agent can propose holding, narrowing a range, widening a range, or reallocating an allowed amount of liquidity. It should explain the expected benefit and the costs. A separate policy layer checks available balances, movement limits, slippage, cooldowns, and data quality before any signer is used.","The executor preserves 20% of claimed assets as reserves, moves at most 15% of one agent-owned position per rebalance, caps swap slippage at 50 bps, enforces a five-minute action cooldown, and holds on a 15% price shock or pool depth below $10,000. Native launch liquidity stays under the bonding curve; after graduation, the original DAMM v2 position stays permanently locked and agents manage additional DLMM liquidity built from earned fees."]},
  {title:"Fees and compounding",paragraphs:["New launches use a 2% fee on the launch curve and graduated DAMM v2 pool. Their companion DLMM pool uses the same launch fee. Earlier coins and already-prepared launches retain their 1.5% configuration. This deployment does not expose model-directed fee changes: the configured native fee structures do not grant the agent arbitrary fee-edit authority. Agents currently adjust ranges and reinvest fees.","The fixed earned-fee allocation is 60% for compounding, 5% for compute, 25% for reserves, and 10% for buying back and burning the main THICC token. Model output cannot change those percentages or choose a payment destination. This fee split is separate from the minimum reserve required for a liquidity position."]},
  {title:"Four models, one boundary",paragraphs:["Fable, Astra, Opus 5.5, and GPT Sol 6.1 share the same permitted actions and validation layer. A more capable model does not receive broader signing authority. OpenRouter handles inference; it does not hold liquidity or execute Solana transactions.","The four names map to anthropic/claude-fable-5.1, openai/gpt-6-astra, anthropic/claude-opus-5.5, and openai/gpt-6.1-sol. No model-ID environment configuration is required. Availability must be checked against OpenRouter. An unavailable model is surfaced as unavailable, rather than replaced with an undisclosed model."]}
 ]},
 {slug:"funding",title:"Compute funded by earned fees.",summary:"Credit replenishment follows observed usage and available fee proceeds. There is no fixed daily dollar ceiling or fixed-dollar top-up.",sections:[
  {title:"10% for THICC buyback and burn",paragraphs:["Every verified fee claim reserves 10% of its proceeds for purchasing and burning the main THICC token. This is a fixed accounting rule, independent of the AI model and the $20 agent activation threshold. It applies to claimed fees, not liquidity principal. The other allocations are 60% compounding, 5% compute, and 25% reserves.","A reservation is created with the fee receipt, once per claim. Small amounts carry forward their rounding remainder. If the main THICC mint is not configured, the reservation waits. It cannot be redirected to compute or liquidity by the model.","Execution begins after a verified claim: swap the reserved fee tokens into THICC, confirm the acquired amount, and burn it using the token program. A submitted transaction must be reconciled before retrying; a failed burn must not trigger another purchase. Completion requires a confirmed burn transaction, not a transfer to a supposed burn wallet.","A missing THICC mint or executable swap route keeps the allocation reserved. Small pending allocations can combine before signing. Acquired THICC is burned with the token program; if the burn is delayed, the worker retries the burn rather than buying again. No completed burn is shown without a finalized burn receipt."]},
  {title:"Where the money comes from",paragraphs:["Only the fee portion allocated to compute can fund inference. LP principal and creator gas funding are excluded. Verified receipts are accounted for before a refill can be planned, and pending deposits reserve their amount so it cannot be allocated twice.","Unlimited daily funding means there is no $25-per-day policy ceiling. It does not mean an unlimited wallet balance, permission to use LP principal, or the ability to spend more than the earned compute budget."]},
  {title:"How the refill amount is chosen",paragraphs:["The monitor samples remaining OpenRouter credits and cumulative usage. It measures the difference in cumulative usage over the last hour. Because this is a usage counter, buying credits does not look like negative spending.","When remaining credits cover roughly two hours of the observed burn rate or less, the system calculates the shortfall to a longer runway. The default is 24 hours. An allowed AI model can forecast a runway between three and 72 hours; the deterministic planner calculates the amount and limits it to available earned compute fees.","For example, an observed $2/hour burn with $4 remaining implies a $44 refill to reach 24 hours of coverage. If only $5 of earned compute fees are available, the system can plan no more than $5. This is an explanatory example, not reported production activity."]},
  {title:"Missing data and duplicate deposits",paragraphs:["The system needs a complete hour of sufficiently recent usage measurements before it derives a refill from that history. Stale data, counter resets, an invalid forecast, or an unconfigured destination keep the planner on hold.","A pending transfer blocks another deposit until its status is reconciled. A retry must first determine whether a transfer was already submitted or credited. Timing out is not evidence that no payment happened."]},
  {title:"The payment route",paragraphs:["The payment flow is earned compute fees, conversion to SOL when needed, a transfer to the platform's verified permanent SolCard deposit address, and OpenRouter's configured card auto-recharge. The public interface summarizes this as OpenRouter funding.","Sending SOL to a card address does not immediately prove that OpenRouter credits were purchased. Solana confirmation, card funding, card charge, and credited inference balance are separate states. The executor sends the configured SOL deposit and waits for a rise in total OpenRouter credits before allowing another funding request. There is no SolCard API connection: the operator configures card auto-recharge separately. An observed credit increase is not a card-processor receipt."]},
  {title:"Funding gas",paragraphs:["Each agent starts with creator-funded gas. Later gas refills may use earned quote-token fees, with an explicit slippage limit and verified prices. A large balance of an illiquid stock or quote token does not guarantee a swap to SOL can be executed safely."]}
 ]},
 {slug:"performance",title:"Measure the agent, not the story.",summary:"The Agents dashboard brings all verified THICC coins together and separates observed outcomes from estimated unmanaged-pool comparisons.",sections:[
  {title:"Platform and coin-level views",paragraphs:["The dashboard shows the number of THICC coins, active agents, managed liquidity, earned position fees, and confirmed fee reinvestment. Each coin shows its model, observation state, rebalances, current fee, and latest recorded action.","The 24-hour, seven-day, and 30-day windows describe the measurement period. Missing telemetry is displayed as unavailable. Aggregate totals require current data coverage rather than quietly adding the few coins that happened to respond."]},
  {title:"The normal-pool comparison",paragraphs:["The baseline uses the actual claimed fees of the original permanently locked native position, excluding companion DLMM fees and AI costs. It holds observed native-pool activity constant, then compares this with the combined measured outcome. It is an observed-flow estimate, not a separate unmanaged-pool replay.","This is not a claim that an identical unmanaged pool actually existed. Traders might have behaved differently if its depth, price, or fees were different. This comparison is not causal proof that an agent created extra volume or return."]},
  {title:"Interpreting the numbers",paragraphs:["Net fee income is earned fees minus gas and AI compute costs. It excludes token-price changes and impermanent loss. Reinvested fees are reported separately and are not counted a second time as income.","A positive difference can be informative, but it is not a promise of profit. A negative difference should be displayed just as clearly. Percentage comparisons are omitted when the unmanaged baseline is zero or negative, because that percentage would be misleading.","Average slippage remains unavailable until comparable trade measurements exist. The baseline and actual costs must cover the same window. Unpriced claims and unknown compute costs prevent a complete net-income comparison. Account rent and unrealized token-price changes are excluded. Repositioned principal is tracked separately from newly reinvested fees."]},
  {title:"Why a dashboard can be empty",paragraphs:["Only verified THICC launches appear in the public directory. There are no unrelated Meteora pools and no seeded demo coins. If nothing has launched or no trustworthy observation exists, empty states are the correct result.","A decision log also distinguishes observation, proposal, rejection, and confirmed execution. A model writing that it intends to rebalance is not evidence that funds moved."]}
 ]},
 {slug:"security",title:"Clear ownership. Honest boundaries.",summary:"The current design uses existing Meteora programs and dedicated agent wallets. It does not require a custom THICC Solana program.",sections:[
  {title:"Creator restrictions versus signer trust",paragraphs:["Native Meteora configuration can assign partner fee claims to the agent wallet while giving the token creator no fee share. That removes fee decisions from the coin creator's launch form and authority path.","A server-managed signing key is still a custody trust boundary. Whoever controls the key can technically sign transactions from that wallet. Server-enforced spending rules are not equivalent to immutable on-chain restrictions. THICC must not claim permanent trustlessness simply because the creator lacks the key."]},
  {title:"What the model never receives",paragraphs:["Inference prompts should contain market observations and permitted strategy parameters, not wallet private keys, RPC credentials, OpenRouter credentials, or arbitrary instructions to choose transfer recipients. The model's response is untrusted input until it passes a strict schema and policy checks.","Signing should happen in a separate constrained execution path with recipient checks, transaction simulation, balance-delta checks, fee budgets, and idempotent submission. These controls live in server code; they are not immutable on-chain wallet restrictions."]},
  {title:"Upgrades, custody, and external dependencies",paragraphs:["Using a native protocol avoids a new custom-program deployment, but it still inherits the protocol's authority model, upgrade behavior, and token support. Permanence claims must be scoped to what the actual deployed program guarantees.","RPC providers, price sources, inference services, card funding, quote issuers, and migration infrastructure can fail independently. The correct response to missing or contradictory evidence is to pause the affected action, preserve funds, and report the state."]},
  {title:"Production readiness",paragraphs:["Native creation, fee claims, migration, swaps, burns, and deposits require deployment-specific live integration verification. Runtime configuration and passing local checks do not prove a funded production transaction has succeeded. Keep backups of both the encrypted database and its separate encryption key.","Observed receipts and published telemetry should be reproducible from transaction evidence. Neither a successful TypeScript build nor a simulated transaction replaces protocol integration testing and an independent security review."]}
 ]}
];
