import {FIXED_SUPPLY_ATOMS,LAUNCH_ECONOMICS} from "./launch-economics";
import {Keypair,PublicKey,SystemProgram,Transaction} from "@solana/web3.js";
import {AuthorityType,ExtensionType,LENGTH_SIZE,TYPE_SIZE,TOKEN_2022_PROGRAM_ID,NATIVE_MINT,createAssociatedTokenAccountIdempotentInstruction,createInitializeMetadataPointerInstruction,createInitializeMintInstruction,createMintToInstruction,createSetAuthorityInstruction,getAssociatedTokenAddressSync,getMint,getMintLen} from "@solana/spl-token";
import {createInitializeInstruction,pack} from "@solana/spl-token-metadata";
import DLMM,{ActivationType,StrategyType,deriveCustomizablePermissionlessLbPair,LBCLMM_PROGRAM_IDS} from "@meteora-ag/dlmm";
import BN from "bn.js";
import {requireQuoteToken} from "./quote-tokens";
import {HttpError,rpc,pubkey} from "./server";
export function atomic(value:string,decimals:number):BN {if(!/^\d+(\.\d+)?$/.test(value))throw new HttpError(400,"Enter a positive token amount.");const [whole,fraction=""]=value.split(".");if(fraction.length>decimals)throw new HttpError(400,`Amount supports at most ${decimals} decimal places.`);const amount=new BN(whole+fraction.padEnd(decimals,"0"));if(amount.isZero()||amount.gt(new BN("18446744073709551615")))throw new HttpError(400,"Token amount is out of range.");return amount;}
export async function packageTransaction(tx:Transaction,payer:PublicKey,signers:Keypair[]=[]){const connection=rpc();const latest=await connection.getLatestBlockhash();tx.feePayer=payer;tx.recentBlockhash=latest.blockhash;if(signers.length)tx.partialSign(...signers);const simulation=await connection.simulateTransaction(tx);if(simulation.value.err)throw new HttpError(400,"Transaction preflight failed. Check balances, token permissions, and pool settings.");const fee=await connection.getFeeForMessage(tx.compileMessage());return {transaction:tx.serialize({requireAllSignatures:false}).toString("base64"),blockhash:latest.blockhash,lastValidBlockHeight:latest.lastValidBlockHeight,networkFeeLamports:fee.value};}
export async function mintToken(wallet:PublicKey,input:{name:string;symbol:string;uri:string}){const connection=rpc();const mint=Keypair.generate();const metadata={updateAuthority:wallet,mint:mint.publicKey,name:input.name,symbol:input.symbol,uri:input.uri,additionalMetadata:[]};const size=getMintLen([ExtensionType.MetadataPointer]);const rent=await connection.getMinimumBalanceForRentExemption(size+TYPE_SIZE+LENGTH_SIZE+pack(metadata).length);const ata=getAssociatedTokenAddressSync(mint.publicKey,wallet,false,TOKEN_2022_PROGRAM_ID);const amount=FIXED_SUPPLY_ATOMS;const tx=new Transaction().add(SystemProgram.createAccount({fromPubkey:wallet,newAccountPubkey:mint.publicKey,space:size,lamports:rent,programId:TOKEN_2022_PROGRAM_ID}),createInitializeMetadataPointerInstruction(mint.publicKey,wallet,mint.publicKey,TOKEN_2022_PROGRAM_ID),createInitializeMintInstruction(mint.publicKey,9,wallet,null,TOKEN_2022_PROGRAM_ID),createInitializeInstruction({programId:TOKEN_2022_PROGRAM_ID,metadata:mint.publicKey,updateAuthority:wallet,mint:mint.publicKey,mintAuthority:wallet,name:input.name,symbol:input.symbol,uri:input.uri}),createAssociatedTokenAccountIdempotentInstruction(wallet,ata,wallet,mint.publicKey,TOKEN_2022_PROGRAM_ID),createMintToInstruction(mint.publicKey,ata,wallet,BigInt(amount.toString()),[],TOKEN_2022_PROGRAM_ID),createSetAuthorityInstruction(mint.publicKey,wallet,AuthorityType.MintTokens,null,[],TOKEN_2022_PROGRAM_ID));return {...await packageTransaction(tx,wallet,[mint]),mint:mint.publicKey.toBase58(),rentLamports:rent};}
export async function createPool(wallet:PublicKey,input:{mint:string;quoteMint:string;price:number;binStep:number;feeBps:number}){const connection=rpc();const mint=pubkey(input.mint);const quoteInfo=await requireQuoteToken(input.quoteMint);const quote=pubkey(quoteInfo.mint);if(mint.equals(quote))throw new HttpError(400,"Base and quote tokens must be different.");const mintInfo=await connection.getAccountInfo(mint);if(!mintInfo)throw new HttpError(400,"Token mint was not found on mainnet.");const token=await getMint(connection,mint,"confirmed",mintInfo.owner);const quoteAccount=await connection.getAccountInfo(quote);if(!quoteAccount)throw new HttpError(400,"Quote mint is unavailable.");const quoteMint=await getMint(connection,quote,"confirmed",quoteAccount.owner);if(quoteMint.decimals!==quoteInfo.decimals)throw new HttpError(400,"Quote registry decimals do not match the chain.");const rawPrice=input.price*Math.pow(10,quoteMint.decimals-token.decimals);const activeId=DLMM.getBinIdFromPrice(rawPrice,input.binStep,false);const tx=await DLMM.createCustomizablePermissionlessLbPair2(connection,new BN(input.binStep),mint,quote,new BN(activeId),new BN(LAUNCH_ECONOMICS.initialFeeBps),ActivationType.Timestamp,false,wallet);const [address]=deriveCustomizablePermissionlessLbPair(mint,quote,new PublicKey(LBCLMM_PROGRAM_IDS["mainnet-beta"]));return {...await packageTransaction(tx,wallet),poolAddress:address.toBase58()};}
export async function addLiquidity(wallet:PublicKey,input:{poolAddress:string;amountX:string;amountY:string;width:number}){const pool=await DLMM.create(rpc(),pubkey(input.poolAddress));const active=await pool.getActiveBin();const position=Keypair.generate();const tx=await pool.initializePositionAndAddLiquidityByStrategy({positionPubKey:position.publicKey,totalXAmount:atomic(input.amountX,pool.tokenX.mint.decimals),totalYAmount:atomic(input.amountY,pool.tokenY.mint.decimals),strategy:{minBinId:active.binId-input.width,maxBinId:active.binId+input.width,strategyType:StrategyType.Curve},user:wallet,slippage:.5});return {...await packageTransaction(tx,wallet,[position]),positionAddress:position.publicKey.toBase58()};}
export async function ownedPositions(wallet:PublicKey,poolAddress:string){const pool=await DLMM.create(rpc(),pubkey(poolAddress));const positions=await pool.getPositionsByUserAndLbPair(wallet);return {pool,positions:positions.userPositions.filter(p=>p.positionData.owner.equals(wallet))};}
