import {sqliteTable,text,integer,real,index} from "drizzle-orm/sqlite-core";
export const accounts=sqliteTable("accounts",{id:text("id").primaryKey(),wallet:text("wallet"),settings:text("settings").notNull().default("{}"),nonce:text("nonce"),nonceExpires:integer("nonce_expires")});
export const agents=sqliteTable("agents",{id:text("id").primaryKey(),owner:text("owner").notNull(),poolAddress:text("pool_address").notNull(),poolName:text("pool_name").notNull(),wallet:text("wallet").notNull(),positionAddress:text("position_address").notNull(),model:text("model").notNull(),policy:text("policy").notNull(),status:text("status").notNull().default("active"),lastRun:integer("last_run"),leaseUntil:integer("lease_until").notNull().default(0)},t=>[index("agents_owner_idx").on(t.owner)]);
export const events=sqliteTable("events",{id:text("id").primaryKey(),owner:text("owner").notNull(),agentId:text("agent_id").notNull(),kind:text("kind").notNull(),message:text("message").notNull(),payload:text("payload"),createdAt:integer("created_at").notNull()},t=>[index("events_owner_idx").on(t.owner,t.createdAt)]);
export const funding=sqliteTable("funding",{id:text("id").primaryKey(),owner:text("owner").notNull(),address:text("address").notNull(),amountUsd:real("amount_usd").notNull(),status:text("status").notNull(),signature:text("signature"),createdAt:integer("created_at").notNull()});
export const snapshots=sqliteTable("snapshots",{id:text("id").primaryKey(),agentId:text("agent_id").notNull(),price:real("price").notNull(),createdAt:integer("created_at").notNull()},t=>[index("snapshots_agent_idx").on(t.agentId,t.createdAt)]);
export const launches=sqliteTable("launches",{id:text("id").primaryKey(),owner:text("owner").notNull(),name:text("name").notNull(),symbol:text("symbol").notNull(),mint:text("mint").notNull(),signature:text("signature").notNull(),poolAddress:text("pool_address"),poolKind:text("pool_kind").notNull().default("dlmm"),description:text("description"),imageUrl:text("image_url"),socialsJson:text("socials_json"),model:text("model"),quoteMint:text("quote_mint"),verifiedAt:integer("verified_at"),createdAt:integer("created_at").notNull()});

export const agentAnalytics=sqliteTable("agent_analytics",{id:text("id").primaryKey(),agentId:text("agent_id").notNull(),window:text("window").notNull(),state:text("state").notNull(),asOf:integer("as_of").notNull(),periodStart:integer("period_start").notNull(),periodEnd:integer("period_end").notNull(),actualJson:text("actual_json").notNull(),baselineJson:text("baseline_json"),verifiedAt:integer("verified_at")},t=>[index("analytics_agent_window_idx").on(t.agentId,t.window,t.asOf)]);
export const creditSnapshots=sqliteTable("credit_snapshots",{observedAt:integer("observed_at").primaryKey(),remainingMicros:text("remaining_micros").notNull(),usedMicros:text("used_micros").notNull()});
export const agentCustody=sqliteTable("agent_custody",{agentId:text("agent_id").primaryKey(),baseMint:text("base_mint").notNull().unique(),wallet:text("wallet").notNull().unique(),encryptedKey:text("encrypted_key").notNull(),poolKind:text("pool_kind").notNull(),configAddress:text("config_address"),createdAt:integer("created_at").notNull()});
export const feeReceipts=sqliteTable("fee_receipts",{signature:text("signature").primaryKey(),agentId:text("agent_id").notNull(),recipient:text("recipient").notNull(),usdMicros:integer("usd_micros").notNull(),computeMicros:integer("compute_micros").notNull(),verifiedAt:integer("verified_at").notNull()},t=>[index("fee_receipts_agent_idx").on(t.agentId)]);
export const feeBuybacks=sqliteTable("fee_buybacks",{claimSignature:text("claim_signature").primaryKey().references(()=>feeReceipts.signature),agentId:text("agent_id").notNull(),usdMicros:integer("usd_micros").notNull(),targetMint:text("target_mint"),status:text("status").notNull().default("awaiting_configuration"),swapSignature:text("swap_signature"),burnSignature:text("burn_signature"),createdAt:integer("created_at").notNull()},t=>[index("fee_buybacks_agent_idx").on(t.agentId)]);
export const fundingMonitor=sqliteTable("funding_monitor",{id:text("id").primaryKey(),leaseUntil:integer("lease_until").notNull().default(0),lastPlan:text("last_plan"),lastForecastAt:integer("last_forecast_at"),targetHours:integer("target_hours").notNull().default(24)});

export const tokenTrades=sqliteTable("token_trades",{id:text("id").primaryKey(),mint:text("mint").notNull(),at:integer("at").notNull(),slot:integer("slot").notNull(),transactionIndex:integer("transaction_index").notNull(),instructionIndex:integer("instruction_index").notNull(),priceUsd:real("price_usd").notNull(),volumeUsd:real("volume_usd").notNull(),verifiedAt:integer("verified_at").notNull()},t=>[index("token_trades_mint_at_idx").on(t.mint,t.at)]);
