import {sql} from "drizzle-orm";
import {sqliteTable,text,integer,real,index,unique,primaryKey,check} from "drizzle-orm/sqlite-core";
export const accounts=sqliteTable("accounts",{id:text("id").primaryKey(),wallet:text("wallet"),settings:text("settings").notNull().default("{}"),nonce:text("nonce"),nonceExpires:integer("nonce_expires")});
export const agents=sqliteTable("agents",{lastTick:integer("last_tick"),id:text("id").primaryKey(),owner:text("owner").notNull(),poolAddress:text("pool_address").notNull(),poolName:text("pool_name").notNull(),wallet:text("wallet").notNull(),positionAddress:text("position_address").notNull(),model:text("model").notNull(),policy:text("policy").notNull(),status:text("status").notNull().default("active"),lastRun:integer("last_run"),leaseUntil:integer("lease_until").notNull().default(0)},t=>[index("agents_owner_idx").on(t.owner)]);
export const events=sqliteTable("events",{id:text("id").primaryKey(),owner:text("owner").notNull(),agentId:text("agent_id").notNull(),kind:text("kind").notNull(),message:text("message").notNull(),payload:text("payload"),createdAt:integer("created_at").notNull()},t=>[index("events_owner_idx").on(t.owner,t.createdAt)]);
export const funding=sqliteTable("funding",{reconciledAt:integer("reconciled_at"),baselineCredits:real("baseline_credits"),id:text("id").primaryKey(),owner:text("owner").notNull(),address:text("address").notNull(),amountUsd:real("amount_usd").notNull(),status:text("status").notNull(),signature:text("signature"),createdAt:integer("created_at").notNull()});
export const snapshots=sqliteTable("snapshots",{id:text("id").primaryKey(),agentId:text("agent_id").notNull(),price:real("price").notNull(),createdAt:integer("created_at").notNull()},t=>[index("snapshots_agent_idx").on(t.agentId,t.createdAt)]);
export const launches=sqliteTable("launches",{quoteDecimals:integer("quote_decimals"),graduationQuote:real("graduation_quote"),id:text("id").primaryKey(),owner:text("owner").notNull(),name:text("name").notNull(),symbol:text("symbol").notNull(),mint:text("mint").notNull(),signature:text("signature").notNull(),poolAddress:text("pool_address"),poolKind:text("pool_kind").notNull().default("dlmm"),description:text("description"),imageUrl:text("image_url"),socialsJson:text("socials_json"),model:text("model"),quoteMint:text("quote_mint"),verifiedAt:integer("verified_at"),createdAt:integer("created_at").notNull()});

export const agentAnalytics=sqliteTable("agent_analytics",{id:text("id").primaryKey(),agentId:text("agent_id").notNull(),window:text("window").notNull(),state:text("state").notNull(),asOf:integer("as_of").notNull(),periodStart:integer("period_start").notNull(),periodEnd:integer("period_end").notNull(),actualJson:text("actual_json").notNull(),baselineJson:text("baseline_json"),verifiedAt:integer("verified_at")},t=>[index("analytics_agent_window_idx").on(t.agentId,t.window,t.asOf)]);
export const creditSnapshots=sqliteTable("credit_snapshots",{observedAt:integer("observed_at").primaryKey(),remainingMicros:text("remaining_micros").notNull(),usedMicros:text("used_micros").notNull()});
export const agentCustody=sqliteTable("agent_custody",{lastActionAt:integer("last_action_at"),dlmmPool:text("dlmm_pool"),graduatedPool:text("graduated_pool"),agentId:text("agent_id").primaryKey(),baseMint:text("base_mint").notNull().unique(),wallet:text("wallet").notNull().unique(),encryptedKey:text("encrypted_key").notNull(),poolKind:text("pool_kind").notNull(),configAddress:text("config_address"),createdAt:integer("created_at").notNull()});
export const feeReceipts=sqliteTable("fee_receipts",{signature:text("signature").primaryKey(),agentId:text("agent_id").notNull(),recipient:text("recipient").notNull(),usdMicros:integer("usd_micros").notNull(),computeMicros:integer("compute_micros").notNull(),verifiedAt:integer("verified_at").notNull()},t=>[index("fee_receipts_agent_idx").on(t.agentId)]);
export const feeBuybacks=sqliteTable("fee_buybacks",{claimSignature:text("claim_signature").primaryKey().references(()=>feeReceipts.signature),agentId:text("agent_id").notNull(),usdMicros:integer("usd_micros").notNull(),targetMint:text("target_mint"),status:text("status").notNull().default("awaiting_configuration"),swapSignature:text("swap_signature"),burnSignature:text("burn_signature"),createdAt:integer("created_at").notNull()},t=>[index("fee_buybacks_agent_idx").on(t.agentId)]);
export const fundingMonitor=sqliteTable("funding_monitor",{id:text("id").primaryKey(),leaseUntil:integer("lease_until").notNull().default(0),lastPlan:text("last_plan"),lastForecastAt:integer("last_forecast_at"),targetHours:integer("target_hours").notNull().default(24)});

export const tokenTrades=sqliteTable("token_trades",{feeUsd:real("fee_usd"),pool:text("pool"),signature:text("signature"),baseAmount:text("base_amount"),quoteAmount:text("quote_amount"),side:text("side"),id:text("id").primaryKey(),mint:text("mint").notNull(),at:integer("at").notNull(),slot:integer("slot").notNull(),transactionIndex:integer("transaction_index").notNull(),instructionIndex:integer("instruction_index").notNull(),priceUsd:real("price_usd").notNull(),volumeUsd:real("volume_usd").notNull(),verifiedAt:integer("verified_at").notNull()},t=>[index("token_trades_mint_at_idx").on(t.mint,t.at)]);

export const launchDrafts=sqliteTable("launch_drafts",{id:text("id").primaryKey(),owner:text("owner").notNull(),wallet:text("wallet").notNull(),inputJson:text("input_json").notNull(),mint:text("mint").notNull(),configAddress:text("config_address").notNull(),poolAddress:text("pool_address").notNull(),agentWallet:text("agent_wallet").notNull(),encryptedKeys:text("encrypted_keys").notNull(),curveJson:text("curve_json").notNull(),imageType:text("image_type").notNull(),imageBase64:text("image_base64").notNull(),metadataJson:text("metadata_json").notNull(),stage:text("stage").notNull().default("config"),createdAt:integer("created_at").notNull()},t=>[index("launch_drafts_owner_idx").on(t.owner,t.createdAt),unique("launch_drafts_agentWallet_unique").on(t.agentWallet),unique("launch_drafts_poolAddress_unique").on(t.poolAddress),unique("launch_drafts_configAddress_unique").on(t.configAddress),unique("launch_drafts_mint_unique").on(t.mint)]);

export const chainOperations=sqliteTable("chain_operations",{id:text("id").primaryKey(),agentId:text("agent_id"),purpose:text("purpose").notNull(),status:text("status").notNull(),wire:text("wire").notNull(),messageHash:text("message_hash").notNull(),signature:text("signature"),lastValidHeight:integer("last_valid_height").notNull(),contextJson:text("context_json").notNull(),resultJson:text("result_json"),error:text("error"),createdAt:integer("created_at").notNull(),updatedAt:integer("updated_at").notNull()},t=>[index("operations_status_idx").on(t.status,t.updatedAt)]);

export const assetClaims=sqliteTable("asset_claims",{id:text("id").primaryKey(),agentId:text("agent_id").notNull(),signature:text("signature").notNull(),mint:text("mint").notNull(),amount:text("amount").notNull(),decimals:integer("decimals").notNull(),usdMicros:integer("usd_micros"),createdAt:integer("created_at").notNull()},t=>[unique("asset_claims_signature_mint_unique").on(t.signature,t.mint)]);

export const assetEntries=sqliteTable("asset_entries",{id:text("id").primaryKey(),agentId:text("agent_id").notNull(),mint:text("mint").notNull(),bucket:text("bucket").notNull(),amount:text("amount").notNull(),operationId:text("operation_id"),createdAt:integer("created_at").notNull()},t=>[index("asset_entries_agent_idx").on(t.agentId,t.mint,t.bucket),check("asset_bucket_check",sql`${t.bucket} IN ('compound','compute','reserve','buyback','burn','recycle')`)]);

export const executionJobs=sqliteTable("execution_jobs",{id:text("id").primaryKey(),agentId:text("agent_id").notNull(),kind:text("kind").notNull(),status:text("status").notNull(),inputMint:text("input_mint").notNull(),inputAmount:text("input_amount").notNull(),outputMint:text("output_mint"),outputAmount:text("output_amount"),contextJson:text("context_json").notNull().default("{}"),retryAt:integer("retry_at").notNull().default(0),attempts:integer("attempts").notNull().default(0),lastError:text("last_error"),createdAt:integer("created_at").notNull(),updatedAt:integer("updated_at").notNull()});

export const poolCursors=sqliteTable("pool_cursors",{pool:text("pool").primaryKey(),newestSignature:text("newest_signature"),beforeSignature:text("before_signature"),targetSignature:text("target_signature"),lastIndexedAt:integer("last_indexed_at")});

export const rawSwaps=sqliteTable("raw_swaps",{id:text("id").primaryKey(),mint:text("mint").notNull(),quoteMint:text("quote_mint").notNull(),quoteDecimals:integer("quote_decimals").notNull(),pool:text("pool").notNull(),signature:text("signature").notNull(),at:integer("at").notNull(),slot:integer("slot").notNull(),transactionIndex:integer("transaction_index").notNull(),instructionIndex:integer("instruction_index").notNull(),side:text("side").notNull(),baseAmount:text("base_amount").notNull(),quoteAmount:text("quote_amount").notNull(),feeQuote:text("fee_quote").notNull()});

export const priceObservations=sqliteTable("price_observations",{mint:text("mint").notNull(),observedAt:integer("observed_at").notNull(),usdPrice:real("usd_price").notNull()},t=>[primaryKey({columns:[t.mint,t.observedAt]})]);

export const poolObservations=sqliteTable("pool_observations",{pool:text("pool").notNull(),observedAt:integer("observed_at").notNull(),slot:integer("slot").notNull(),priceQuote:real("price_quote").notNull(),priceUsd:real("price_usd").notNull(),liquidityUsd:real("liquidity_usd").notNull(),quoteReserve:text("quote_reserve").notNull(),baseReserve:text("base_reserve").notNull()},t=>[primaryKey({columns:[t.pool,t.observedAt]})]);

export const agentPositions=sqliteTable("agent_positions",{address:text("address").primaryKey(),agentId:text("agent_id").notNull(),pool:text("pool").notNull(),kind:text("kind").notNull(),createdAt:integer("created_at").notNull()});

export const runtimeLocks=sqliteTable("runtime_locks",{id:text("id").primaryKey(),token:text("token").notNull(),expiresAt:integer("expires_at").notNull()});

export const modelCalls=sqliteTable("model_calls",{id:text("id").primaryKey(),agentId:text("agent_id").notNull(),model:text("model").notNull(),status:text("status").notNull(),costUsd:real("cost_usd"),reservedUsd:real("reserved_usd").notNull(),generationId:text("generation_id"),createdAt:integer("created_at").notNull()});
